/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gr.charos.apps.ptt.app;

import gr.charos.apps.ptt.list.LinkedList;

import static gr.charos.apps.ptt.utilities.StringUtils.join;
import static gr.charos.apps.ptt.utilities.StringUtils.split;
import static gr.charos.apps.ptt.app.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        String result = join(tokens);
        System.out.println(WordUtils.capitalize(result));
    }
}
