/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("gr.charos.apps.ptt.java-library-conventions")
}

dependencies {
    api(project(":domain"))  
    api("com.google.firebase:firebase-admin:8.1.0")
    api("com.google.code.gson:gson:2.8.9")
    
    api("org.projectlombok:lombok:1.18.22")
    
    
    testCompile("junit:junit:4.12")
    
    
}
