/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("gr.charos.apps.ptt.java-library-conventions")
}

tasks.withType<JavaCompile> {
	val compilerArgs = options.compilerArgs
	compilerArgs.add("--enable-preview")
}